# Generated by Django 4.2 on 2026-06-22 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(help_text='Price in Rs.')),
                ('description', models.TextField()),
                ('tag', models.CharField(help_text="Short feature tag, e.g. 'Summer friendly breathable cotton.'", max_length=200)),
                ('badge', models.CharField(blank=True, choices=[('', '— None —'), ('Bestseller', 'Bestseller'), ('New Drop', 'New Drop'), ('Limited', 'Limited'), ('Premium', 'Premium'), ('Essential', 'Essential'), ('Artisan', 'Artisan')], default='', max_length=20)),
                ('category', models.CharField(choices=[('Outerwear', 'Outerwear'), ('Hoodies', 'Hoodies'), ('Tees', 'Tees'), ('Bottoms', 'Bottoms'), ('Dresses', 'Dresses'), ('Accessories', 'Accessories'), ('Shirts', 'Shirts'), ('Knitwear', 'Knitwear')], default='Outerwear', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('image1', models.CharField(help_text='Filename in static/images/ (e.g. product1.jpg)', max_length=200)),
                ('image2', models.CharField(blank=True, help_text='Alt view filename in static/images/ (e.g. product1_2.jpg)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only active products appear on the site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.PositiveIntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
